### ISSUE TITLE
on windows 

### ISSUE THREAD

**Issue by chengjianxi** [wandenberg/nginx-video-thumbextractor-module#10]
does nginx-video-thumbextractor-module support on windows platform?

**Comment by wandenberg** [comment]
If you can get all the requirements working on windows it should work.

**Comment by chengjianxi** [comment]
i got error

ngx_http_video_thumbextractor_module_ipc.c(96): warning C4013: “pipe” Undefined
ngx_http_video_thumbextractor_module_ipc.c(96): warning C4013:  “fcntl"  Undefined
"F_GETFD" Undeclared
"FD_CLOEXEC" Undeclared
"F_SETFD" Undeclared

**Comment by wandenberg** [comment]
@chengjianxi you are right, after I changed to use a forked process to create the image it depends on the `inter process communication`. 
You can try to use an older version of the module or build using the `linux inside the windows` (never tried)

**Comment by chengjianxi** [comment]
why not compatible windows?

**Comment by wandenberg** [comment]
no specific reason other than is more code to write and keep working and the majority of the servers  run on unix like. :)
But you can make it compatible.

**Comment by chengjianxi** [comment]
your are right, i will give up windows. 
Too much nginx module not compatible with windows.
