### ISSUE TITLE
Crop_Ctx issue

### ISSUE THREAD

**Issue by siaro30** [wandenberg/nginx-video-thumbextractor-module#13]
Hi , i have a this errors.  

cc -c -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Werror -g -I/usr/local/include  -I src/core  -I src/event  -I src/event/modules  -I src/os/unix  -I ../modules/nginx-rtmp-module-master  -I ../modules/nginx-video-thumbextractor-module-master/src  -I ../modules/nginx-video-thumbextractor-module-master/include  -I /usr/local/include/libxml2  -I /usr/local/include  -I objs  -I src/http  -I src/http/modules  -I src/http/v2  -I src/mail  -I src/stream  -o objs/addon/src/ngx_http_video_thumbextractor_module.o  ../modules/nginx-video-thumbextractor-module-master/src/ngx_http_video_thumbextractor_module.c
In file included from ../modules/nginx-video-thumbextractor-module-master/src/ngx_http_video_thumbextractor_module.c:28:
../modules/nginx-video-thumbextractor-module-master/src/ngx_http_video_thumbextractor_module_utils.c:566:55: error: variable 'crop_ctx' may be uninitialized when used here
      [-Werror,-Wconditional-uninitialized]
        if (rc >= 0) rc = avfilter_link(scale_ctx, 0, crop_ctx, 0);
                                                      ^~~~~~~~
../modules/nginx-video-thumbextractor-module-master/src/ngx_http_video_thumbextractor_module_utils.c:429:30: note: initialize the variable 'crop_ctx' to silence this
      warning
    AVFilterContext *crop_ctx;
                             ^
                              = NULL
../modules/nginx-video-thumbextractor-module-master/src/ngx_http_video_thumbextractor_module_utils.c:554:47: error: variable 'transpose_ctx' may be uninitialized when used
      here [-Werror,-Wconditional-uninitialized]
        rc = avfilter_link(*buffersrc_ctx, 0, transpose_ctx, 0);
                                              ^~~~~~~~~~~~~
../modules/nginx-video-thumbextractor-module-master/src/ngx_http_video_thumbextractor_module_utils.c:426:35: note: initialize the variable 'transpose_ctx' to silence this
      warning
    AVFilterContext *transpose_ctx;
                                  ^
                                   = NULL
../modules/nginx-video-thumbextractor-module-master/src/ngx_http_video_thumbextractor_module_utils.c:556:63: error: variable 'transpose_cw_ctx' may be uninitialized when
      used here [-Werror,-Wconditional-uninitialized]
            if (rc >= 0) rc = avfilter_link(transpose_ctx, 0, transpose_cw_ctx, 0);
                                                              ^~~~~~~~~~~~~~~~
../modules/nginx-video-thumbextractor-module-master/src/ngx_http_video_thumbextractor_module_utils.c:427:38: note: initialize the variable 'transpose_cw_ctx' to silence
      this warning
    AVFilterContext *transpose_cw_ctx;
                                     ^
                                      = NULL
3 errors generated.
*** Error code 1

Stop.
make[1]: stopped in /root/nginx-1.12.1
*** Error code 1

Stop.
make: stopped in /root/nginx-1.12.1

ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
  configuration: --prefix=/usr/local --mandir=/usr/local/man --datadir=/usr/local/share/ffmpeg --pkgconfigdir=/usr/local/libdata/pkgconfig --enable-shared --enable-pic --enable-gpl --enable-postproc --enable-avfilter --enable-avresample --enable-pthreads --cc=cc --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcelt --disable-chromaprint --enable-libdc1394 --disable-stripping --enable-htmlpages --enable-libfdk-aac --enable-ffserver --enable-libflite --enable-fontconfig --enable-libfreetype --enable-frei0r --enable-libfribidi --enable-libgme --enable-libgsm --enable-iconv --enable-libilbc --enable-libkvazaar --enable-ladspa --enable-libmp3lame --enable-libbluray --enable-mmx --enable-libmodplug --enable-netcdf --enable-openal --enable-opencl --enable-libopencv --enable-opengl --enable-libopenh264 --enable-libopenjpeg --enable-optimizations --enable-libopus --enable-libpulse --enable-runtime-cpudetect --enable-librubberband --enable-libschroedinger --enable-ffplay --disable-libsmbclient --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-sse --disable-libssh --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libv4l2 --enable-vaapi --enable-vdpau --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --disable-gcrypt --disable-gmp --enable-librtmp --disable-gnutls --enable-openssl --enable-version3 --enable-nonfree
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100

**Comment by wandenberg** [comment]
Try to replace the lines at the beginner of the `setup_filters` function with 
```
    AVFilterGraph   *filter_graph = NULL;

    AVFilterContext *transpose_ctx = NULL;
    AVFilterContext *transpose_cw_ctx = NULL;
    AVFilterContext *scale_ctx = NULL;
    AVFilterContext *crop_ctx = NULL;
    AVFilterContext *tile_ctx = NULL;
    AVFilterContext *format_ctx = NULL;
```

They will be initialized when needed but the syntax analyzer is not seeing this. It depends on the version of gcc/clang and the parameters used.

**Comment by siaro30** [comment]
Hi wandenberg , 
Its compiled , and work .But an error began to recur. 

2017/10/03 11:38:34 [alert] 4762#100123: kqueue close() failed (9: Bad file descriptor)
2017/10/03 11:39:17 [alert] 4838#100118: kqueue close() failed (9: Bad file descriptor)
2017/10/03 11:39:31 [alert] 4839#100123: kqueue close() failed (9: Bad file descriptor)
2017/10/03 11:39:36 [alert] 4840#100123: kqueue close() failed (9: Bad file descriptor)
2017/10/03 11:39:44 [alert] 4841#100142: kqueue close() failed (9: Bad file descriptor)
2017/10/03 11:41:07 [alert] 5026#100142: kqueue close() failed (9: Bad file descriptor)


Gives jpeg  out, but he makes an error like this.

**Comment by wandenberg** [comment]
Can you try to reproduce the problem in a vagrant machine or in a docker container? 
Will be easier to investigate.
