### ISSUE TITLE
Support for older FFMPEG or FFMPEG in LTS distributions

### ISSUE THREAD

**Issue by theyosh** [wandenberg/nginx-video-thumbextractor-module#14]
Hi,

it is not handy to create modules that depends on latest source code of FFMPEG. This means that we have to compile manually FFMPEG first before this module can be used.

Is it possible to support Ubuntu LTS versions? That means using an older ffmpeg and containing libraries? I can not imagine that the code to extract thumbnails uses that exotic code. Now we have the following error:

`cc -c -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2 -DNDK_SET_VAR -I/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_rtmp_module  -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/http/modules/perl -I /home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx-development-kit/objs -I objs/addon/ndk -I /home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx-development-kit/src -I /home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx-development-kit/objs -I objs/addon/ndk -I /home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nchan/src -I /home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx-lua/src/api -I /usr/include/luajit-2.0 -I /home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_video_thumbextractor_module/src -I /home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_video_thumbextractor_module/include -I /usr/include/libxml2 -I /home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_rtmp_module -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I /home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx-development-kit/src -I src/mail -I src/stream \
	-o objs/addon/src/ngx_http_video_thumbextractor_module.o \
	/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_video_thumbextractor_module/src/ngx_http_video_thumbextractor_module.c
In file included from /home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_video_thumbextractor_module/src/ngx_http_video_thumbextractor_module.c:28:0:
/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_video_thumbextractor_module/src/ngx_http_video_thumbextractor_module_utils.c: In function ‘ngx_http_video_thumbextractor_get_thumb’:
/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_video_thumbextractor_module/src/ngx_http_video_thumbextractor_module_utils.c:164:5: warning: implicit declaration of function ‘avcodec_parameters_to_context’ [-Wimplicit-function-declaration]
     avcodec_parameters_to_context(pCodecCtx, pFormatCtx->streams[videoStream]->codecpar);
     ^
/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_video_thumbextractor_module/src/ngx_http_video_thumbextractor_module_utils.c:164:78: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’
     avcodec_parameters_to_context(pCodecCtx, pFormatCtx->streams[videoStream]->codecpar);
                                                                              ^
/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_video_thumbextractor_module/src/ngx_http_video_thumbextractor_module_utils.c: In function ‘get_frame’:
/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_video_thumbextractor_module/src/ngx_http_video_thumbextractor_module_utils.c:632:17: warning: implicit declaration of function ‘avcodec_send_packet’ [-Wimplicit-function-declaration]
             if (avcodec_send_packet(pCodecCtx, &packet) == AVERROR(EAGAIN)) continue;
                 ^
/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/modules/nginx_video_thumbextractor_module/src/ngx_http_video_thumbextractor_module_utils.c:633:33: warning: implicit declaration of function ‘avcodec_receive_frame’ [-Wimplicit-function-declaration]
             if ((decodeStatus = avcodec_receive_frame(pCodecCtx, pFrame)) == AVERROR(EAGAIN)) continue;
                                 ^
objs/Makefile:1464: recipe for target 'objs/addon/src/ngx_http_video_thumbextractor_module.o' failed
make[3]: *** [objs/addon/src/ngx_http_video_thumbextractor_module.o] Error 1
make[3]: Leaving directory '/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/build-extras'
Makefile:8: recipe for target 'build' failed
make[2]: *** [build] Error 2
make[2]: Leaving directory '/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1/debian/build-extras'
debian/rules:169: recipe for target 'build.arch.extras' failed
make[1]: *** [build.arch.extras] Error 2
make[1]: Leaving directory '/home/joshua/Desktop/nginx-JS-modules/tmp.gbbXO8iyal/nginx-1.12.1'
debian/rules:147: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
`

**Comment by wandenberg** [comment]
Hi @theyosh you can use an old version of the module like 0.8.0. 
It is also hard to support the module with all the available FFMpeg/libraries versions.
If we find a bug that also applies to an old version of the module, independent of the libraries version than I can provide a version like 0.8.1 fixing the bug.

**Comment by theyosh** [comment]
Adding PPA: https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-3 has solved it for me
