### ISSUE TITLE
video thumb extractor module: Seek to an invalid time while sending to client, client

### ISSUE THREAD

**Issue by abdullaha1** [wandenberg/nginx-video-thumbextractor-module#16]
my config

 location ~ /api/videos/(\d+)/(\d+)/(\d+)(/.*)$ {
		 root   /home/dev/apps/itsplenty-services/media;

		add_header Content-Disposition 'attachment';
                proxy_set_header Accept-Encoding "deflate, gzip";
                proxy_set_header Accept "*/*";
                proxy_http_version 1.1;
                proxy_method GET;
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";
               
	        video_thumbextractor;
	        video_thumbextractor_video_filename $4;
		video_thumbextractor_video_second      $3;
	        video_thumbextractor_image_width       $1;
	        video_thumbextractor_image_height      $2;

		add_header Content-Disposition 'attachment';
                error_page   415 = /empty;

		 }

**Comment by wandenberg** [comment]
Hi, @abdullaha1 sorry for the delay.
Unfortunately, I could not understand what is your issue.
Please provide more details, versions that you are using for the module, Nginx and FFMpeg, and preferable the video causing the issue. Is easier to help/fix an issue when can reproduce it.

**Comment by abdullaha1** [comment]
I fixed it
