### ISSUE TITLE
Generate "storyboard" of a given video

### ISSUE THREAD

**Issue by flavioribeiro** [wandenberg/nginx-video-thumbextractor-module#7]
I took a look at Youtube thumbs preview and could notice that they create a single image with frames concatenated, like the [image](https://i.ytimg.com/sb/VplITGI8Znk/storyboard3_L1/M0.jpg?sigh=butlqhJRY5_DpGzAjZgR08EPxMo) below:

![image](https://cloud.githubusercontent.com/assets/244265/5889534/7118527c-a413-11e4-8edd-3302c49c2d08.png)

This leads to a more fluid seekbar navigation since the frames appear faster (just changing the visible window in css, in case the seekbar is made by DOM elements, for example).  I'm wondering if it's possible to create this feature inside the module itself, what do you think?

**Comment by wandenberg** [comment]
This feature was on my thoughts for a long time.

Now that I changed the module to work with the library avfilter probably this can be done in a easier way.
I'm trying to map the steps that ffmpeg does execute with the tile filter to reproduce them inside the module.

If you have any idea how to implement it, any help is welcome.

**Comment by wandenberg** [comment]
Solved with 4211eec5b1815fb047cc9be9ca2bb33c2473afae

**Comment by flavioribeiro** [comment]
:+1:
